# Generated by Django 5.1.4 on 2025-01-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="goal",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
